server:
  port: 5432

spring:
  application:
    name: library
  profiles:
    active:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate