server:
  port: 8999

spring:
  application:
    name: redtag
  profiles:
    active:
  datasource:
    url: jdbc:postgresql://localhost:2000/redtag
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate