server:
  port: 3000

spring:
  flyway:
    baseline-on-migrate: true
  application:
    name: library
  profiles:
    active:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update